# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'advaccarello@gmail.com'
  config.password       = 'Charterbus1'
  config.integrator_key = 'SUBO-3c2009a9-9592-4a30-9448-2ced662de1e0'
  config.account_id     = '72a9c941-8f39-4c00-b254-589cedf038ef'
  #config.endpoint       = 'https://www.docusign.net/restapi'
  #config.api_version    = 'v1'
end

