development:
  recaptcha:
    public_key: 6LdFoAQTAAAAAA28FgNB_PYKvoM7kJao5IpbPp3I
    private_key: 6LdFoAQTAAAAAOBIJlIbT23uKuZGcTfyxsRCcitq
  s3:
    access_key_id: AKIAJTDJKWWUJZD42BBA
    secret_access_key: "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"
    bucket: subout-test
test:
  recaptcha:
    public_key: 6LdFoAQTAAAAAA28FgNB_PYKvoM7kJao5IpbPp3I
    private_key: 6LdFoAQTAAAAAOBIJlIbT23uKuZGcTfyxsRCcitq
  s3:
    access_key_id: AKIAJTDJKWWUJZD42BBA
    secret_access_key: "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"
    bucket: subout-test
subouttest:
  recaptcha:
    public_key: 6LdFoAQTAAAAAA28FgNB_PYKvoM7kJao5IpbPp3I
    private_key: 6LdFoAQTAAAAAOBIJlIbT23uKuZGcTfyxsRCcitq
  s3:
    access_key_id: AKIAJTDJKWWUJZD42BBA
    secret_access_key: "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"
    bucket: subout-test
production:
  recaptcha:
    public_key: 6LdFoAQTAAAAAA28FgNB_PYKvoM7kJao5IpbPp3I
    private_key: 6LdFoAQTAAAAAOBIJlIbT23uKuZGcTfyxsRCcitq
  s3:
    access_key_id: AKIAJTDJKWWUJZD42BBA
    secret_access_key: "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"
    bucket: subout-production